name: Go
on: [push]
jobs:

  test:
    name: Test
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        go: [ '1.19.x', '1.20.x', '1.21.x' ]
    runs-on: ${{ matrix.go }}
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Test
      run: go test -v -race ./...